# Generated by Django 5.1.3 on 2024-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='priceNow',
        ),
        migrations.AddField(
            model_name='itemdata',
            name='priceNewest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='phsm',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='priceWeekAgo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='timeRefreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
