# Generated by Django 5.1.3 on 2024-12-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdata',
            old_name='timeRefreshed',
            new_name='time_refreshed',
        ),
    ]
